### ISSUE TITLE
the world model of bugtrap is incorrect

### ISSUE THREAD

**Issue by citaer** [jtorde/planning_worlds_gazebo#3]
I put the world file in gazebo9, but I find that every block's gravity parameters are "0,0,0" but not "0 0 -9.8". And every block have no collision setting, robot even can go through wall. Besides, the bag file have only a pointcloud message, could you tell me what's the use of this pointcloud?

**Comment by jtorde** [comment]
Hi @citaer,

All the worlds have the physics engine disabled by default. You can enable it by not launching [this plugin](https://github.com/jtorde/planning_worlds_gazebo/blob/master/src/forest/density01seed0.world#L3). 

Moreover, you may want to change all the [gravity fields](https://github.com/jtorde/planning_worlds_gazebo/blob/master/src/forest/density01seed0.world#L134) to `<gravity>0 0 -9.8</gravity>` 

(the reason why both the physics engine and the gravity were disabled in the worlds is that the use of these worlds was simply to generate the depth image coming from the depth camera of the robot. Disabling the physics makes the simulation run much faster). 

You can use the .bag to visualize the world in rviz. You can publish it by running `rosbag play bugtrap.bag -l`

Let me know if this helps!

**Comment by citaer** [comment]
Thank you for your suggestion, the bag info shows that it has only 0.0s. Does the bag just show one frame of the depth camera?

**Comment by jtorde** [comment]
Yes, the bag just has one point cloud of the whole world. The option `-l` when doing `rosbag play` will keep publishing it indefinitely.

**Comment by jtorde** [comment]
(I'm closing this for now, but feel free to reopen it if you are still having this issue)
